version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: docker build
          command: |
            sudo apt-get update
            sudo apt-get install -y golang
            export PATH=$(go env GOPATH)/bin:$PATH
            mkdir -p $(go env GOPATH)/bin
            mkdir -p $(go env GOPATH)/src/github.com/cosmopetrich
            cd $(go env GOPATH)/src/github.com/cosmopetrich
            git clone -b master --single-branch --depth 1 https://github.com/cosmopetrich/twitter_stream_exporter.git
            cd twitter_stream_exporter
            curl https://glide.sh/get | sh
            glide install
            VERSION=$(git describe --always --dirty
            SHA1=$(git rev-parse --short --verify HEAD
            BUILD_DATE=$(date -u +%F-%T
            go build -ldflags "-extldflags -static -X main.VERSION=${VERSION} -X main.COMMIT_SHA1=${SHA1} -X main.BUILD_DATE=${BUILD_DATE}"
            mv twitter_stream_exporter ~/repo
            cd ~/repo
            docker build -t build .
      - deploy:
          name: deploy
          command: |
            set -u

            DOCKER_TAG=$DOCKER_USER/buildenv_docker:$CIRCLE_BRANCH
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag build $DOCKER_TAG
            docker push $DOCKER_TAG

            if [ "$CIRCLE_BRANCH" == "master" ]; then
              DOCKER_TAG_LATEST=$DOCKER_USER/twitter_stream_exporter_docker:latest
              docker tag build $DOCKER_TAG_LATEST
              docker push $DOCKER_TAG_LATEST
            fi
